title: Alex Brown
description: Landing page for relevant links
baseurl: ""
url: https://piazzai.github.io/cvless

theme: cvless

# site settings
taglong: Deepening my knowledge in Cybersecurity
tagshort: Landing page
cv: false # This needs to be turned to true for generation of CV

# author settings
author:
  name: Alex Brown
  email: alex@digitallycrafted.tech
photo: assets/files/photo.jpg
address: 1234 NoNeedToKnow St.
phone: 111-222-3333

# profile links
profile:
  # facebook: https://www.facebook.com/username
  # x: https://x.com/username
  # mastodon: https://mastodon.social/@username
  # bluesky: https://bsky.app/profile/username.bsky.social
  # instagram: https://www.instagram.com/username
  linkedin: https://www.linkedin.com/in/digitallycrafted
  # xing: https://www.xing.com/profile/username
  # stackoverflow: https://stackoverflow.com/users/0000000/username
  # medium: https://medium.com/@username
  # github: https://github.com/username

# build settings
permalink: pretty
exclude:
  - LICENSE
  - demo/
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
