name: Sync Fork with Upstream

on:
  schedule:
    # Runs every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # Checkout the forked repository
    - name: Checkout fork
      uses: actions/checkout@v3

    # Add the upstream repository
    - name: Add Upstream Repository
      run: |
        git remote add upstream https://github.com/Lifes-A-Glitch/alexcv.lifesaglitch.io.gitt
        git fetch upstream

    # Sync the fork with the upstream repository
    - name: Sync with Upstream
      run: |
        git checkout master
        git merge upstream/master
        git push origin master
